modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# 我们 Mixin 进 InfuserMenu 的私有构造器，因此限定在 8.0.x 区间：
# 若灌注台在 8.1 改动该签名，我们的 @Invoker 会失配，宁可在此直接拦住。
[[dependencies.${mod_id}]]
    modId="enchantinginfuser"
    mandatory=true
    versionRange="[8.0.3,8.1)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="puzzleslib"
    mandatory=true
    versionRange="[8.1.13,)"
    ordering="NONE"
    side="BOTH"

# 我们调用 ApothEnchantmentMenu.gatherStats / EnchModule.getEnchInfo
# 以及 EnchantingRecipe.findMatch，全部来自神化附魔模块。
[[dependencies.${mod_id}]]
    modId="apotheosis"
    mandatory=true
    versionRange="[7.4.8,8.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="placebo"
    mandatory=true
    versionRange="[8.6.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="attributeslib"
    mandatory=true
    versionRange="[1.3.5,)"
    ordering="NONE"
    side="BOTH"
